### ISSUE TITLE
Right Side Top-Section Lines Shape.

### ISSUE THREAD

**Issue by d2Dreamer** [TowneSquare/web-v2#14]
Shape does not match Figma Design - fix and extend beyond first screen as shown. 

Current: 
![image](https://github.com/TowneSquare/web-v2/assets/41088824/64595632-8e6c-4c65-9a90-fe5dadd44b8c)

Design:
![image](https://github.com/TowneSquare/web-v2/assets/41088824/dc27e7ac-8b60-4eeb-94b1-8b22484040de)

**Comment by codewizard870** [comment]
- merge 2 svgs on top right side
