### ISSUE TITLE
Update button label from "Get early access" to "Join waitlist"

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/web-v2#22]
<img width="644" alt="Screenshot 2023-07-18 at 10 48 27" src="https://github.com/TowneSquare/web-v2/assets/139227890/6bdf5440-0b75-4e64-9f43-657b9eca90c8">
<img width="547" alt="Screenshot 2023-07-18 at 10 48 43" src="https://github.com/TowneSquare/web-v2/assets/139227890/40d776c0-3831-4f3f-affc-a2a1e18e44b8">

**Comment by d2Dreamer** [comment]
Fixed - 
![image](https://github.com/TowneSquare/web-v2/assets/41088824/0557872f-fbad-4f10-a835-3eadcdd996ce)
![image](https://github.com/TowneSquare/web-v2/assets/41088824/760f2585-af1d-4bdd-bf9c-bd880d01500c)
