### ISSUE TITLE
Vision section bg element (right bottom corner)

### ISSUE THREAD

**Issue by markots** [TowneSquare/web-v2#23]
Rn when you scroll from introduction to the vision section, bg element in right bottom corner have fix position and feels like is discovered. The bg element need to appear and move from bottom together with other elements in Vision section.

**How is looking** 
<img width="1660" alt="Screenshot 2023-07-18 alle 11 11 43" src="https://github.com/TowneSquare/web-v2/assets/112094900/dc6c475a-3746-4744-b932-44b71bfec1e5">

https://github.com/TowneSquare/web-v2/assets/112094900/fb6a56eb-d7e5-4729-83c7-17ced8528aa5

**How need to look**
<img width="658" alt="Screenshot 2023-07-18 alle 11 14 56" src="https://github.com/TowneSquare/web-v2/assets/112094900/6c797316-4b21-4270-a4e6-9ccaa30f0900">

https://github.com/TowneSquare/web-v2/assets/112094900/e965d42d-9022-4f9b-a1a1-ff74b2fc0727

**Comment by Helme0315** [comment]
@d2Dreamer 
@markots 
How about this vision bg element?

https://github.com/TowneSquare/web-v2/assets/32021912/a8966cfa-f24d-44b1-ad21-fb0085bfd192
