### ISSUE TITLE
Riname btn to "Join waitlist"

### ISSUE THREAD

**Issue by markots** [TowneSquare/web-v2#26]
<img width="1662" alt="Screenshot 2023-07-18 alle 17 52 08" src="https://github.com/TowneSquare/web-v2/assets/112094900/4b73dfe7-1c82-4dcf-9b86-f95e4a19ecb8">

**Comment by d2Dreamer** [comment]
![image](https://github.com/TowneSquare/web-v2/assets/41088824/4e20872a-ae90-49f1-ab0e-7352934784cc)
Fixed.
